# Generated by Django 6.0.1 on 2026-01-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_movie_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='video_url',
            field=models.CharField(default='', max_length=500),
        ),
    ]
