# Generated by Django 6.0.1 on 2026-01-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_movie_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='video_url',
        ),
        migrations.AddField(
            model_name='movie',
            name='video_id',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
