# Generated by Django 6.0.1 on 2026-01-28 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.CharField(choices=[('avatar1.png', 'Avatar 1'), ('avatar2.jpg', 'Avatar 2'), ('avatar3.jpg', 'Avatar 3'), ('avatar4.jpg', 'Avatar 4')], default='avatar1.png', max_length=50),
        ),
    ]
