# Generated by Django 6.0.1 on 2026-02-05 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_profile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_kids',
        ),
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('random', 'random'), ('vlog', 'vlog'), ('cultural', 'cultural'), ('family', 'family')], default='random', max_length=50),
        ),
    ]
