# Generated by Django 6.0.1 on 2026-02-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='download_devices',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='resolution',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='simultaneous_streams',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='supported_devices',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='video_sound_quality',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='duration_days',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
