# Generated by Django 6.0.1 on 2026-02-16 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_subscriptionplan_download_devices_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='price',
            new_name='Monthly_price',
        ),
    ]
