# Generated by Django 6.0.1 on 2026-02-16 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_rename_price_subscriptionplan_monthly_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='Monthly_price',
            new_name='price',
        ),
    ]
